name: Deploy Cron

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image for Cron
      uses: docker/build-push-action@v5
      with:
        file: ./apps/cron/Dockerfile.cron
        push: true
        tags: ghcr.io/joinvalley/v2-cron:latest

    - name: Deploy Cron to DigitalOcean App Platform
      uses: digitalocean/app_action@v1.1.6
      with:
        app_name: joinvalley-v2-cron
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Notify Slack on Failure
      if: failure()
      uses: ./.github/workflows/slack-alert.yml
      with:
        status: 'Failure'
        message: 'Cron deployment failed'
