name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  determine-affected:
    runs-on: ubuntu-latest
    outputs:
      api-affected: ${{ steps.affected.outputs.api }}
      worker-affected: ${{ steps.affected.outputs.worker }}
      cron-affected: ${{ steps.affected.outputs.cron }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Install Nx
        run: pnpm add -D nx

      - name: Set Nx SHAs
        run: |
          # Get the current commit SHA
          echo "Current commit SHA: $(git rev-parse HEAD)"
          # Save it to a file for later use
          echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Determine Affected Projects
        id: affected
        run: |
          npx nx print-affected --base=origin/main --head=$(git rev-parse HEAD) > affected.json
          cat affected.json
          echo "::set-output name=api::$(grep -q '"apps/api"' affected.json && echo true || echo false)"
          echo "::set-output name=worker::$(grep -q '"apps/worker"' affected.json && echo true || echo false)"
          echo "::set-output name=cron::$(grep -q '"apps/cron"' affected.json && echo true || echo false)"

  build-and-deploy:
    needs: determine-affected
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Install Nx
        run: pnpm add -D nx

      - name: Run Prisma migrations
        run: pnpm prisma:no-doppler migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image for API
        if: needs.determine-affected.outputs.api-affected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile.api
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy API to DigitalOcean App Platform
        if: needs.determine-affected.outputs.api-affected == 'true'
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: joinvalley-v2-api
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and Push Docker Image for Worker
        if: needs.determine-affected.outputs.worker-affected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy Worker to DigitalOcean App Platform
        if: needs.determine-affected.outputs.worker-affected == 'true'
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: joinvalley-v2-worker
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and Push Docker Image for Cron
        if: needs.determine-affected.outputs.cron-affected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/cron/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/cron:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy Cron to DigitalOcean App Platform
        if: needs.determine-affected.outputs.cron-affected == 'true'
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: joinvalley-v2-cron
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: failure()
    steps:
      - name: Send failure notification to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "The GitHub Actions workflow for deploying the services has failed. Please check the logs for more details."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
